.TH QTOX 1 "September 2014"

.SH NAME
qtox - GUI Tox client

.SH SYNOPSIS
.B qtox

.SH DESCRIPTION
.B qtox
is a graphical Tox client with the following features:
.br
   - one-to-one chat with friends
.br
   - group chats
.br
   - file transfers with image preview
.br
   - audio calls
.br
   - video calls
.br

.SH OPTIONS
.BI qtox
has no command line options.

.SH SEE ALSO
.br
.B Homepage:
http://utoxisfinished.info
.br

.B Tox Wiki:
https://wiki.tox.im/QTox
.br

.SH AUTHOR
This manual page was written by kytv <killyourtv@i2pmail.org> for the Debian system (but may be used by others).
.br
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation
.br
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
